---
- name: install keyboard-configuration
  apt:
    name: keyboard-configuration
    state: present
- name: write keyboard configration
  template:
    src: keyboards.txt
    dest: /etc/default/keyboard
    force: true
- name: apply keyboard configration
  command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
