---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-keyboard-debian-wheezy
    image: debian:7

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default/playbook.yml
    prepare: ../default/prepare.yml
  lint:
    name: ansible-lint

scenario:
  name: debian-min

verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
